# From: https://github.com/marketplace/actions/compile-arduino-sketches
# Uses: https://github.com/arduino/compile-sketches
name: Arduino Compile Sketches

on: 
  push:
  workflow_dispatch:
    inputs:
      message:
        description: Message to display in job summary
        required: false
        type: string

jobs:
  compile-sketches: 
    strategy:
      matrix:
        include:
          - arch: avr32u4
            fqbn: 'arduino:avr:micro'
            platform-name: 'arduino:avr'
            platform-sourceurl: 'https://downloads.arduino.cc/packages/package_index.json'
          - arch: avr328
            fqbn: 'arduino:avr:uno'
            platform-name: 'arduino:avr'
            platform-sourceurl: 'https://downloads.arduino.cc/packages/package_index.json'
          - arch: stm32
            fqbn: 'STMicroelectronics:stm32:GenF1:pnum=BLUEPILL_F103C8'
            platform-name: 'STMicroelectronics:stm32'
            platform-sourceurl: 'https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json'
          - arch: esp8266
            fqbn: 'esp8266:esp8266:thing'
            platform-name: 'esp8266:esp8266'
            platform-sourceurl: 'http://arduino.esp8266.com/stable/package_esp8266com_index.json'
          - arch: esp32
            fqbn: 'esp32:esp32:esp32'
            platform-name: 'esp32:esp32'
            platform-sourceurl: 'https://espressif.github.io/arduino-esp32/package_esp32_index.json'

    name: call-compile-sketches-workflow
    uses: Andy4495/.github/.github/workflows/arduino-compile-sketches.yml@main
    with:
      message: ${{ inputs.message }}
      copyfile: 
      fqbn: ${{ matrix.fqbn }}
      platform-name: ${{ matrix.platform-name }}
      platform-sourceurl: ${{ matrix.platform-sourceurl }}
      platform-version: latest
      libraries: |
        - source-path: ./
        - name: SD
        - source-url: https://github.com/ppedro74/Arduino-SerialCommands.git