# GitHub Action from: https://github.com/gaurav-nelson/github-action-markdown-link-check
# Uses code from: https://github.com/tcort/markdown-link-check
name: Check Markdown Links

on: 
  push:
  schedule:
    # Modify the cron time to a somewhat random day/time to avoid having all your repos running at the same time
    # Run 4th day of every month at 4:41 AM (See https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07)
    - cron: "37 4 4 * *"
  workflow_dispatch:
    inputs:
      message:
        description: Message to display in job summary
        required: false
        type: string
jobs:
  markdown-link-check:
    name: call-markdown-link-check-workflow
    uses: Andy4495/.github/.github/workflows/CheckMarkdownLinks.yml@main         
    with:
      message: ${{ inputs.message }}
            
